//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lapy.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLaptop
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Product { get; set; }
        public string price { get; set; }
        public string SPrice { get; set; }
        public string Date { get; set; }
        public string Model_no { get; set; }
    }
}
